### ISSUE TITLE
快捷键问题

### ISSUE THREAD

**Issue by beautifulzyb** [xhhjin/SearchCrutch#1]
我使用的是 firefox 浏览器，在使用过程中发现如下情况：
1.自动切换快捷键 “ ctrl + shift + Y " 与自带的历史记录快捷键冲突，且找不到地方重置此快捷键按钮。
2.搜索引擎相对位置无法改变，即假设我选择了谷歌、百度、必应与360搜索，无法直接从谷歌跳转至必应搜索。
3.所有更改并非即时生效，必须重启后生效（我不知道是不是所有的扩展都这样）
如上所述，其实第2和第3都是可有可无的功能，但是第一个功能真的很重要啊，请作者适当予以考虑添加快捷键设置按钮，感激感激。。。

**Comment by xhhjin** [comment]
非常感谢你的反馈，对于你的问题 1， 3，我这边用最新的 Firefox 61.0.1 (32 位)  并没有发现问题：
1，最早开发时考虑过设置快捷键，但在 Firefox 下并没有找到便捷的实现方法，同样的代码在 Chrome 下是可以设置的，建议你参考 [Firefox 键盘快捷键](https://support.mozilla.org/zh-CN/kb/%E9%94%AE%E7%9B%98%E5%BF%AB%E6%8D%B7%E9%94%AE)页面，用其推荐的 [Saka key](https://addons.mozilla.org/firefox/addon/saka-key/) 扩展定制 Firefox 快捷键试试；
2，这个实现得多加好多快捷键，容易产生冲突，如果对默认排序感觉不好，可以全部用自定义，配置一个适合自己的顺序；
3，目前最新版测试是改完即生效的，早期有些版本是改完刷新下需要切换的页面才生效。
另外，你可将你所用 Firefox 版本发我测试下。

**Comment by beautifulzyb** [comment]
你好，感谢你的回复，我使用的版本信息如下：
![default](https://user-images.githubusercontent.com/13692270/43949814-2f5b7ab2-9cc1-11e8-9078-ee8279a99d4a.png)
我的键盘快捷键页面内容中，有一项是这样的：
![default](https://user-images.githubusercontent.com/13692270/43949868-56961f56-9cc1-11e8-96fc-b33dcc935de8.png)

**Comment by xhhjin** [comment]
原来是 Linux 的，快捷键和 Windows 还不一样啊，已针对 Linux 修改了，更新下版本吧，用 Ctrl+Shift+B 来切换前一个。
