### ISSUE TITLE
无法从自定义搜索切出

### ISSUE THREAD

**Issue by chenpey** [xhhjin/SearchCrutch#11]
添加了自定义搜索之后，点击能切到自定义搜索，但是再次点击切不出来了，无限循环在自定义搜索里面
只添加了一个Bing国际版，内容如下：
https://www.bing.com/search?mkt=zh-SG&cc=sg&q=%s

**Comment by xhhjin** [comment]
测试了下，没有发现问题，估计和浏览器有关系，可以清除下 cookies 什么的重新试试。
