### ISSUE TITLE
chrome新版本插件 自定义搜索引擎不支持循环切换了

### ISSUE THREAD

**Issue by KinglyWayne** [xhhjin/SearchCrutch#12]
设置快捷键之后, 自定义的搜索引擎快捷键(向前或者向后) 不再支持循环了, 
跟之前版本有差别, 使用起来需要设置两个快捷键, 建议是否能恢复到之前的可循环切换模式?

**Comment by xhhjin** [comment]
请确认下版本是否最新的 V3.30，中间有个版本有bug，最好插件卸载重装下，测试过应该是可以循环切换的
