### ISSUE TITLE
啥时候支持Edge浏览器？

### ISSUE THREAD

**Issue by dcdb723** [xhhjin/SearchCrutch#6]
如题

**Comment by xhhjin** [comment]
新版本的 Edge 已经支持直接从 chrome 商店安装扩展了。

**Comment by xhhjin** [comment]
Edge 外接程序已发布：[点击安装](https://microsoftedge.microsoft.com/addons/detail/%E6%90%9C%E7%B4%A2%E6%8B%90%E6%9D%96/cniecfnnkipcbgnbopieadadhpppfjlm)
