### ISSUE TITLE
在google无法访问且chrome尝试连接时，切换至其他引擎

### ISSUE THREAD

**Issue by sunzhen6251** [xhhjin/SearchCrutch#9]
感谢作者！插件非常好用！但有一个问题一直困扰：我访问Google不是很稳定。在google不通的情况下，使用 chrome 的地址栏进行 google 搜索，会有 20 多秒的尝试加载时间。在此时已知道 google 无法访问，但无法使用插件切换至其他搜索引擎。直到出现“无法访问此网站”的页面时，才能使用插件切换到百度搜索。

有无办法在出现“无法访问此网站”之前，切换至其他搜索引擎？

谢谢！

**Comment by xhhjin** [comment]
谢谢支持，不过这个好像不行，你可以先点击停止加载此页的按钮试试。

**Comment by sunzhen6251** [comment]
谢谢回复！我研究了一下，尝试连接google时应该还属于webRequest阶段，tab页上并没有事件触发，按停止后tab上的url属性仍是newtab（虽然地址栏上是google的搜索链接），所以，看样子的确不好处理了……
